# 100 numpy exercises

Python code in one module gains access to the code in another module by the process of importing it

1. Import the numpy package under the name np
       np also called alias name for numpy package      

In [1]:
import numpy as np

2. Print the numpy version and the configuration.

      These syntax use for check numpy version and confiruered.

In [3]:
print(np.__version__)

1.18.2


3. Create a null vector of size 10 

In [4]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. How to find the memory size of any array 

In [8]:
print(x.size * x.itemsize,  "bytes")


80 bytes


5. Write a NumPy program to multiply a matrix by another matrix of complex numbers and create a new matrix of complex numbers.

In [9]:
import numpy as np
x = np.array([1+2j,3+4j])
print("First array:")
print(x)
y = np.array([5+6j,7+8j])
print("Second array:")
print(y)
z = np.vdot(x, y)
print("Product of above two arrays:")
print(z)

First array:
[1.+2.j 3.+4.j]
Second array:
[5.+6.j 7.+8.j]
Product of above two arrays:
(70-8j)


6. Create a null vector of size 10 but the fifth value which is 1

In [10]:
x = np.zeros(10)
print(x)
print("Update fifth value to 1")
x[5] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update fifth value to 1
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49

In [11]:
y = np.linspace(10,49)
print(y)


[10.         10.79591837 11.59183673 12.3877551  13.18367347 13.97959184
 14.7755102  15.57142857 16.36734694 17.16326531 17.95918367 18.75510204
 19.55102041 20.34693878 21.14285714 21.93877551 22.73469388 23.53061224
 24.32653061 25.12244898 25.91836735 26.71428571 27.51020408 28.30612245
 29.10204082 29.89795918 30.69387755 31.48979592 32.28571429 33.08163265
 33.87755102 34.67346939 35.46938776 36.26530612 37.06122449 37.85714286
 38.65306122 39.44897959 40.24489796 41.04081633 41.83673469 42.63265306
 43.42857143 44.2244898  45.02040816 45.81632653 46.6122449  47.40816327
 48.20408163 49.        ]


8. Reverse a vector (first element becomes last)

In [12]:
x = np.arange(12, 38)
print("Original array:")
print(x)
print("Reverse array:")
x = x[::-1]
print(x)

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


9. Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
z =  np.arange(0, 9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [19]:
nums = np.array([1,2,0,0,4,0])
print("Original array:")
print(nums)
print("Indices of elements not equal to zero of the said array:")
result = np.where(nums != 0)[0]
print(result)

Original array:
[1 2 0 0 4 0]
Indices of elements not equal to zero of the said array:
[0 1 4]


11. Create a 3x3 identity matrix 

In [21]:
a=np.identity(3)
print('3x3 matrix:')
print(a)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Create a 3x3x3 array with random values

In [23]:
b = np.random.random((3,3,3))
print(b)


[[[0.63108992 0.63360112 0.68022349]
  [0.98132175 0.9337579  0.0495567 ]
  [0.00988264 0.73195979 0.44081572]]

 [[0.56633398 0.19634299 0.66885708]
  [0.39271624 0.70429542 0.88188984]
  [0.69406704 0.42743722 0.92669952]]

 [[0.78706961 0.20844786 0.65811544]
  [0.84546689 0.21831613 0.67076179]
  [0.19169448 0.21259113 0.82992976]]]


13. Create a 10x10 array with random values and find the minimum and maximum values 

In [25]:
c = np.random.random((10,10))
print("Original Array:")
print(c) 
xmin, xmax = c.min(), c.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.63500943 0.57342814 0.33970207 0.29810264 0.7950192  0.33822312
  0.65400462 0.96286117 0.44772601 0.75995098]
 [0.07378215 0.92031809 0.13441711 0.58522507 0.0824805  0.55036687
  0.72417867 0.3420072  0.4226856  0.86667264]
 [0.65723571 0.04110764 0.70333604 0.93540188 0.85833585 0.54802274
  0.34596218 0.26311322 0.03444569 0.92462648]
 [0.8261954  0.21263754 0.32744535 0.66578534 0.43455573 0.90277269
  0.02911962 0.31722211 0.03349491 0.23055454]
 [0.24107664 0.5906291  0.98059139 0.51133039 0.7691446  0.37971801
  0.19372392 0.07255116 0.75657189 0.72586154]
 [0.62782586 0.30764857 0.68064252 0.31063377 0.22654282 0.69105822
  0.27271657 0.88905233 0.37798126 0.37867674]
 [0.04137282 0.33578501 0.37418972 0.23567416 0.3315583  0.32690167
  0.30882541 0.16003049 0.78971666 0.82205344]
 [0.68515886 0.45909984 0.99769963 0.24122295 0.2911417  0.81044973
  0.0550643  0.92442787 0.98783945 0.04927552]
 [0.01607662 0.11729306 0.50134187 0.79648025 0.21604892 0.76177

14. Create a random vector of size 30 and find the mean value

In [28]:
d = np.random.random(30)
print("Original array:")
print(d)
d.mean()

Original array:
[1.01558611e-01 1.95870904e-01 2.55252189e-01 2.96119304e-01
 2.81844415e-01 9.42847764e-02 9.74334559e-01 5.97905383e-01
 3.51358012e-03 7.89679005e-01 6.90075379e-01 2.84634986e-01
 9.14729589e-02 7.95702368e-01 8.03959154e-01 5.14716625e-01
 1.10989328e-01 4.43093483e-01 3.00317962e-01 6.63712401e-01
 4.02226019e-02 4.72569609e-01 8.65470500e-01 3.28926395e-01
 7.56706872e-01 7.02145454e-01 4.87565519e-04 7.10649136e-01
 9.25035964e-01 5.00733353e-01]


0.4530661607797092

15. Create a 2d array with 1 on the border and 0 inside 

In [37]:
x = np.ones((5,5))
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array?

In [38]:
e = np.ones((3,3))
print("Original array:")
print(e)
print("0 on the border and 1 inside in the array")
e = np.pad(e, pad_width=1, mode='constant', constant_values=0)
print(e)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


17. What is the result of the following expression? 

In [47]:
a = 0 * np.nan
print(a)
b = np.nan == np.nan
print(b)
c = np.inf > np.nan
print(c)
d = np.nan - np.nan
print(d)
e = np.nan in set([np.nan])
print(e)
f = 0.3 == 3 * 0.1
print(f)

nan
False
False
nan
True
False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [61]:
x = np.diag([1, 2, 3, 4, 5],k=-1)
print(x)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [63]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

21. Create a checkerboard 8x8 matrix using the tile function ***

22. Normalize a 5x5 random matrix 

In [88]:
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.68724101 0.52548162 0.95163835 0.51638954 0.75965753]
 [0.73275459 0.05673693 0.00218838 0.9963216  0.42168189]
 [0.4135928  0.45992329 0.56803079 0.84244628 0.60234873]
 [0.05395639 0.07335903 0.23106518 0.89680915 0.1718498 ]
 [0.1363997  0.85403767 0.55492546 0.64086498 0.7364955 ]]
After normalization:
[[0.6890954  0.52638141 0.95505305 0.51723567 0.76193927]
 [0.73487757 0.05487046 0.         1.         0.42196911]
 [0.41383228 0.46043618 0.56918167 0.8452166  0.60370214]
 [0.05207352 0.07159066 0.2302275  0.89990029 0.17066266]
 [0.13500335 0.85687639 0.555999   0.64244569 0.73864056]]


23. Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array.

In [89]:
x = np.array([-1.6, -1.5, -0.3, 0.1, 1.4, 1.8, 2.0])
print("Original array:")
print(x)
print("Floor values of the above array elements:")
print(np.floor(x))
print("Ceil values of the above array elements:")
print(np.ceil(x))
print("Truncated values of the above array elements:")
print(np.trunc(x))

Original array:
[-1.6 -1.5 -0.3  0.1  1.4  1.8  2. ]
Floor values of the above array elements:
[-2. -2. -1.  0.  1.  1.  2.]
Ceil values of the above array elements:
[-1. -1. -0.  1.  2.  2.  2.]
Truncated values of the above array elements:
[-1. -1. -0.  0.  1.  1.  2.]


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [90]:
x = np.random.random((5,3))
print("First array:")
print(x)
y = np.random.random((3,2))
print("Second array:")
print(y)
z = np.dot(x, y)
print("Dot product of two arrays:")
print(z)

First array:
[[0.85875587 0.46331808 0.5055545 ]
 [0.16901486 0.87790653 0.8751936 ]
 [0.54229694 0.24144963 0.95738449]
 [0.27598326 0.20958368 0.97364138]
 [0.24349139 0.78235863 0.67722388]]
Second array:
[[0.83331557 0.26664712]
 [0.14372246 0.26246732]
 [0.15508418 0.53990759]]
Dot product of two arrays:
[[0.86060736 0.62354335]
 [0.40274628 0.74801277]
 [0.63508141 0.72487371]
 [0.41109941 0.65427538]
 [0.42037439 0.63590816]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [100]:
a = np.arange(11)
print(a)
a[3:9] = np.negative(a[3:9])
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


26. What is the output of the following script?

27. Write a NumPy program to get the element-wise remainder of an array of division.

In [103]:
x = np.arange(7)
print("Original array:")
print(x)
print("Element-wise remainder of division:")
print(np.remainder(x, 5))

Original array:
[0 1 2 3 4 5 6]
Element-wise remainder of division:
[0 1 2 3 4 0 1]


28. Write a NumPy program to get the powers of an array values element-wise

In [104]:
x = np.arange(7)
print("Original array")
print(x)
print("First array elements raised to powers from second array, element-wise:")
print(np.power(x, 3))

Original array
[0 1 2 3 4 5 6]
First array elements raised to powers from second array, element-wise:
[  0   1   8  27  64 125 216]


29. How to round away from zero a float array ?

In [105]:
x = np.round([1.45, 1.50, 1.55])
print(x)
x = np.round([0.28, .50, .64], decimals=1)
print(x)
x = np.round([.5, 1.5, 2.5, 3.5, 4.5]) # rounds to nearest even value
print(x)

[1. 2. 2.]
[0.3 0.5 0.6]
[0. 2. 2. 4. 4.]


30. How to find common values between two arrays?

In [106]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


31. Write a NumPy program to get the largest integer smaller or equal to the division of the inputs

In [107]:
x = [1., 2., 3., 4.]
print("Original array:")
print(x)
print("Largest integer smaller or equal to the division of the inputs:")
print(np.floor_divide(x, 1.5))

Original array:
[1.0, 2.0, 3.0, 4.0]
Largest integer smaller or equal to the division of the inputs:
[0. 1. 2. 2.]


32. Is the following expressions true? 

33. How to get the dates of yesterday, today and tomorrow?

In [109]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yesterday:  2020-12-17
Today:  2020-12-18
Tomorrow:  2020-12-19


34. How to get all the dates corresponding to the month of July 2016?

In [110]:
print("July, 2016")
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

July, 2016
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [111]:
A = np.ones(3)*1

B = np.ones(3)*2

C = np.ones(3)*3

np.add(A,B,out=B)

np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

36. Extract the integer part of a random array using 5 different methods

In [114]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)

print (np.floor(Z))

print (np.ceil(Z)-1)

print (Z.astype(int))

[5. 6. 8. 9. 6. 8. 9. 2. 2. 3.]
[5. 6. 8. 9. 6. 8. 9. 2. 2. 3.]
[5. 6. 8. 9. 6. 8. 9. 2. 2. 3.]
[5 6 8 9 6 8 9 2 2 3]


37. Create a 5x5 matrix with row values ranging from 0 to 4

In [120]:
Z = np.zeros((5,5))

Z += np.arange(5)

print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


38. Consider a generator function that generates 10 integers and use it to build an array

In [125]:
def generate():

    for x in range(10):

        yield x

Z = np.fromiter(generate(),dtype=float,count=-1)

print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [126]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1]

print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40. Create a random vector of size 10 and sort it

In [132]:
R = np.random.random(10)

R.sort()
print(R)


[0.02988904 0.2285731  0.27727165 0.49409921 0.50898213 0.58503551
 0.77535291 0.83066601 0.86529308 0.98950481]


41. How to sum a small array faster than np.sum?

In [133]:
Z = np.arange(10)

np.add.reduce(Z)

45

42. Consider two random array A and B, check if they are equal

In [137]:
A = np.random.randint(0,2,5)

B = np.random.randint(0,2,5)

equal = np.allclose(A,B)

print(equal)

equal = np.array_equal(A,B)

print(equal)

False
False


43. Write a NumPy program to get true division of the element-wise array inputs.

44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [138]:
Z = np.random.random((10,2))

X,Y = Z[:,0], Z[:,1]

R = np.sqrt(X**2+Y**2)

T = np.arctan2(Y,X)

print(R)

print(T)

[1.0116166  1.0043861  1.10984418 0.61623875 1.20630127 0.88669915
 0.60981926 0.67181713 1.11921705 0.97651445]
[1.37896735 0.10818419 0.86794468 0.86606481 0.87366396 1.45804466
 1.29004957 0.31934796 0.65980362 1.25882417]


45. Create random vector of size 10 and replace the maximum value by 0

In [139]:
Z = np.random.random(10)

Z[Z.argmax()] = 0

print(Z)

[0.02124051 0.41329998 0.12355421 0.41865797 0.51408949 0.12242447
 0.14165205 0.76953315 0.33919306 0.        ]


46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

In [140]:
Z = np.zeros((5,5), [('x',float),('y',float)])

Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),

np.linspace(0,1,5))

print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))


In [141]:
X = np.arange(8)

Y = X + 0.5

C = 1.0 / np.subtract.outer(X, Y)

print(np.linalg.det(C))

3638.163637117973


48. Print the minimum and maximum representable value for each numpy scalar type

In [146]:
for dtype in [np.int8, np.int32, np.int64]:

    print(np.iinfo(dtype).min)

    print(np.iinfo(dtype).max)


for dtype in [np.float32, np.float64]:

            print(np.finfo(dtype).min)

            print(np.finfo(dtype).max)

            print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


49. Write a NumPy program to add, subtract, multiply, divide arguments element-wise.
Sample elements: 4.0, 1.2

In [147]:
import numpy as np
print("Add:")
print(np.add(1.0, 4.0))
print("Subtract:")
print(np.subtract(1.0, 4.0))
print("Multiply:")
print(np.multiply(1.0, 4.0))
print("Divide:")
print(np.divide(1.0, 4.0))


Add:
5.0
Subtract:
-3.0
Multiply:
4.0
Divide:
0.25


50. How to find the closest value (to a given scalar) in a vector?

In [148]:
Z = np.arange(100)

v = np.random.uniform(0,100)

index = (np.abs(Z-v)).argmin()

print(Z[index])

12


51. Write a NumPy program to generate a matrix product of two arrays.

In [149]:
x = [[1, 0], [1, 1]]
y = [[3, 1], [2, 2]]
print("Matrices and vectors.")
print("x:")
print(x)
print("y:")
print(y)
print("Matrix product of above two arrays:")
print(np.matmul(x, y))

Matrices and vectors.
x:
[[1, 0], [1, 1]]
y:
[[3, 1], [2, 2]]
Matrix product of above two arrays:
[[3 1]
 [5 3]]


52.Write a NumPy program to find the roots of the following polynomials.
a) x2 − 4x + 7.
b) x4 − 11x3 + 9x2 + 11x – 10

In [150]:
print("Roots of the first polynomial:")
print(np.roots([1, -2, 1]))
print("Roots of the second polynomial:")
print(np.roots([1, -12, 10, 7, -10]))

Roots of the first polynomial:
[1. 1.]
Roots of the second polynomial:
[11.04461946+0.j        -0.8711421 +0.j         0.91326132+0.4531004j
  0.91326132-0.4531004j]


53.  Write a NumPy program to convert an array to a float type.

In [151]:
a = [1, 2, 3, 4]
print("Original array")
print(a)
x = np.asfarray(a)
print("Array converted to a float type:")
print(x)

Original array
[1, 2, 3, 4]
Array converted to a float type:
[1. 2. 3. 4.]


54. Write a NumPy program to find the real and imaginary parts of an array of complex numbers.

In [152]:
x = np.sqrt([1+0j])
y = np.sqrt([0+1j])
print("Original array:x ",x)
print("Original array:y ",y)
print("Real part of the array:")
print(x.real)
print(y.real)
print("Imaginary part of the array:")
print(x.imag)
print(y.imag)


Original array:x  [1.+0.j]
Original array:y  [0.70710678+0.70710678j]
Real part of the array:
[1.]
[0.70710678]
Imaginary part of the array:
[0.]
[0.70710678]


56. Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

In [153]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [0, 40]
print("Array2: ",array2)
print("Compare each element of array1 and array2")
print(np.in1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [0, 40]
Compare each element of array1 and array2
[ True False False  True False]


57. Write a NumPy program to find common values between two arrays.

In [154]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))


Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


58. Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.

In [155]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values in array1 that are not in array2:")
print(np.setdiff1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values in array1 that are not in array2:
[ 0 20 60 80]


59.Write a NumPy program to find the union of two arrays. Union will return the unique, sorted array of values that are in either of the two input arrays.

In [156]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique sorted array of values that are in either of the two input arrays:")
print(np.union1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique sorted array of values that are in either of the two input arrays:
[ 0 10 20 30 40 50 60 70 80]


60. Write a NumPy program to test whether all elements in an array evaluate to True.
Note: 0 evaluates to False in python

In [157]:
print(np.all([[True,False],[True,True]]))
print(np.all([[True,True],[True,True]]))
print(np.all([10, 20, 0, -50]))
print(np.all([10, 20, -50]))

False
True
False
True


61. Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.

In [158]:
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))

Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


62. Write a NumPy program to save a NumPy array to a text file.

In [160]:
a = np.arange(1.0, 2.0, 36.2)
np.savetxt('file.out', a, delimiter=',')

63.Write a NumPy program to create a contiguous flattened array.

In [161]:
x = np.array([[10, 20, 30], [20, 40, 50]])
print("Original array:")
print(x)
y = np.ravel(x)
print("New flattened array:")
print(y)

Original array:
[[10 20 30]
 [20 40 50]]
New flattened array:
[10 20 30 20 40 50]


64. Write a NumPy program to change the data type of an array. 

In [162]:
import numpy as np
x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(x)
print("Data type of the array x is:",x.dtype)
# Change the data type of x
y = x.astype(float)
print("New Type: ",y.dtype)
print(y)


[[ 2  4  6]
 [ 6  8 10]]
Data type of the array x is: int32
New Type:  float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


65. Write a NumPy program to create a 3-D array with ones on a diagonal and zeros elsewhere.

In [163]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


66.  Write a NumPy program to generate six random integers between 10 and 30

In [164]:
x = np.random.randint(low=10, high=30, size=6)
print(x)

[19 22 14 12 10 22]


67.  Write a NumPy program to check two random arrays are equal or not.

In [165]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)


First array:
[0 1 0 0 1 0]
Second array:
[1 1 1 1 0 0]
Test above two arrays are equal or not!
False


68. Write a NumPy program to find the most frequent value in an array.

In [166]:
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[7 2 3 4 8 5 4 0 9 3 5 8 9 2 4 2 7 7 6 7 0 8 8 0 8 4 5 8 5 8 7 0 7 3 2 0 5
 4 2 8]
Most frequent value in the above array:
8


69. Write a NumPy program to get the n largest values of an array.

In [167]:
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


70. Write a NumPy program to shuffle numbers between 0 and 10

In [168]:
import numpy as np
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))

[9 1 5 7 6 0 8 3 4 2]
Same result using permutation():
[7 9 6 5 3 2 8 0 4 1]


71. Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.

In [169]:
a = np.array([[10,40],[30,20]])
print("Original array:")
print(a)
print("Sort the array along the first axis:")
print(np.sort(a, axis=0))
print("Sort the array along the last axis:")
print(np.sort(a))
print("Sort the flattened array:")
print(np.sort(a, axis=None))

Original array:
[[10 40]
 [30 20]]
Sort the array along the first axis:
[[10 20]
 [30 40]]
Sort the array along the last axis:
[[10 40]
 [20 30]]
Sort the flattened array:
[10 20 30 40]


72. Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height.

In [170]:
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]
# create a structured array
students = np.array(students_details, dtype=data_type)   
print("Original array:")
print(students)
print("Sort by height")
print(np.sort(students, order='height'))    

Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]
Sort by height
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


73.  Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort by class, then height if class are equal

In [173]:
print(np.sort(students, order='class'))    
print(np.sort(students, order=['class', 'height']))


[(b'James', 5, 48.5 ) (b'Paul', 5, 42.1 ) (b'Pit', 5, 40.11)
 (b'Nail', 6, 52.5 )]
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


74. Write a NumPy program to sort the student id with increasing height of the students from given students id and height. Print the integer indices that describes the sort order by multiple columns and the sorted data.

In [174]:
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
student_height = np.array([40., 42., 45., 41., 38., 40., 42.0])
#Sort by studen_id then by student_height
indices = np.lexsort((student_id, student_height))
print("Sorted indices:")
print(indices)
print("Sorted data:")
for n in indices:
  print(student_id[n], student_height[n])

Sorted indices:
[4 0 5 3 6 1 2]
Sorted data:
1682 38.0
1023 40.0
5241 40.0
1671 41.0
4532 42.0
5202 42.0
6230 45.0


75.  Write a NumPy program to get the indices of the sorted elements of a given array.

In [175]:
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
print("Original array:")
print(student_id)
i = np.argsort(student_id)
print("Indices of the sorted elements of a given array:")
print(i)

Original array:
[1023 5202 6230 1671 1682 5241 4532]
Indices of the sorted elements of a given array:
[0 3 4 6 1 5 2]


76. Write a NumPy program to sort a given complex array using the real part first, then the imaginary part.

In [176]:
complex_num = [1 + 2j, 3 - 1j, 3 - 2j, 4 - 3j, 3 + 5j]
print("Original array:")
print(complex_num)
print("\nSorted a given complex array using the real part first, then the imaginary part.")
print(np.sort_complex(complex_num))

Original array:
[(1+2j), (3-1j), (3-2j), (4-3j), (3+5j)]

Sorted a given complex array using the real part first, then the imaginary part.
[1.+2.j 3.-2.j 3.-1.j 3.+5.j 4.-3.j]


77. Write a NumPy program to partition a given array in a specified position and move all the smaller elements values to the left of the partition, and the remaining values to the right, in arbitrary order

In [177]:
nums = np.array([70, 50, 20, 30, -11, 60, 50, 40])
print("Original array:")
print(nums)
print("\nAfter partitioning on 4 the position:")
print(np.partition(nums, 4))

Original array:
[ 70  50  20  30 -11  60  50  40]

After partitioning on 4 the position:
[-11  30  20  40  50  50  60  70]


78. Write a NumPy program to round array elements to the given number of decimals.

In [178]:
x = np.round([1.45, 1.50, 1.55])
print(x)
x = np.round([0.28, .50, .64], decimals=1)
print(x)
x = np.round([.5, 1.5, 2.5, 3.5, 4.5]) # rounds to nearest even value
print(x)

[1. 2. 2.]
[0.3 0.5 0.6]
[0. 2. 2. 4. 4.]


79. Write a NumPy program to round elements of the array to the nearest integer

In [180]:
x = np.array([-.7, -1.5, -1.7, 0.3, 1.5, 1.8, 2.0])
print("Original array:")
print(x)
x = np.rint(x)
print("Round elements of the array to the nearest integer:")
print(x)

Original array:
[-0.7 -1.5 -1.7  0.3  1.5  1.8  2. ]
Round elements of the array to the nearest integer:
[-1. -2. -2.  0.  2.  2.  2.]


80. Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array.

In [181]:
x = np.array([-1.6, -1.5, -0.3, 0.1, 1.4, 1.8, 2.0])
print("Original array:")
print(x)
print("Floor values of the above array elements:")
print(np.floor(x))
print("Ceil values of the above array elements:")
print(np.ceil(x))
print("Truncated values of the above array elements:")
print(np.trunc(x))

Original array:
[-1.6 -1.5 -0.3  0.1  1.4  1.8  2. ]
Floor values of the above array elements:
[-2. -2. -1.  0.  1.  1.  2.]
Ceil values of the above array elements:
[-1. -1. -0.  1.  2.  2.  2.]
Truncated values of the above array elements:
[-1. -1. -0.  0.  1.  1.  2.]


81. Write a NumPy program to multiply a matrix by another matrix of complex numbers and create a new matrix of complex numbers

In [182]:
x = np.array([1+2j,3+4j])
print("First array:")
print(x)
y = np.array([5+6j,7+8j])
print("Second array:")
print(y)
z = np.vdot(x, y)
print("Product of above two arrays:")
print(z)

First array:
[1.+2.j 3.+4.j]
Second array:
[5.+6.j 7.+8.j]
Product of above two arrays:
(70-8j)


82. Write a NumPy program to create an inner product of two arrays.

In [184]:
x = np.arange(24).reshape((2,3,4))
print("Array x:")
print(x)
print("Array y:")
y = np.arange(4)
print(y)
print("Inner of x and y arrays:")
print(np.inner(x, y))

Array x:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Array y:
[0 1 2 3]
Inner of x and y arrays:
[[ 14  38  62]
 [ 86 110 134]]


83. Write a NumPy program to generate inner, outer, and cross products of matrices and vectors.

In [185]:
x = np.array([1, 4, 0], float)
y = np.array([2, 2, 1], float)
print("Matrices and vectors.")
print("x:")
print(x)
print("y:")
print(y)
print("Inner product of x and y:")
print(np.inner(x, y))
print("Outer product of x and y:")
print(np.outer(x, y))
print("Cross product of x and y:")
print(np.cross(x, y))

Matrices and vectors.
x:
[1. 4. 0.]
y:
[2. 2. 1.]
Inner product of x and y:
10.0
Outer product of x and y:
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
Cross product of x and y:
[ 4. -1. -6.]


84. Write a NumPy program to compute the following polynomial values.

85.  Write a NumPy program to calculate mean across dimension, in a 2D numpy array.

In [187]:
x = np.array([[10, 30], [20, 60]])
print("Original array:")
print(x)
print("Mean of each column:")
print(x.mean(axis=0))
print("Mean of each row:")
print(x.mean(axis=1))


Original array:
[[10 30]
 [20 60]]
Mean of each column:
[15. 45.]
Mean of each row:
[20. 40.]


86.  Write a NumPy program to convert angles from degrees to radians for all elements in a given array.

In [188]:
x = np.array([-180.,  -90.,   90.,  180.])
r1 = np.radians(x)
r2 = np.deg2rad(x)
assert np.array_equiv(r1, r2)
print(r1)

[-3.14159265 -1.57079633  1.57079633  3.14159265]


87.  Write a NumPy program to concatenate element-wise two arrays of string

In [189]:
x1 = np.array(['Python', 'PHP'], dtype=np.str)
x2 = np.array([' Java', ' C++'], dtype=np.str)
print("Array1:")
print(x1)
print("Array2:")
print(x2)
new_array = np.char.add(x1, x2)
print("new array:")
print(new_array)


Array1:
['Python' 'PHP']
Array2:
[' Java' ' C++']
new array:
['Python Java' 'PHP C++']


88. Write a NumPy program to repeat all the elements three times of a given array of string

In [190]:
x1 = np.array(['Python', 'PHP', 'Java', 'C++'], dtype=np.str)
print("Original Array:")
print(x1)
new_array = np.char.multiply(x1, 3)
print("New array:")
print(new_array)

Original Array:
['Python' 'PHP' 'Java' 'C++']
New array:
['PythonPythonPython' 'PHPPHPPHP' 'JavaJavaJava' 'C++C++C++']


89. Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array.

In [191]:
x = np.array(['python', 'PHP', 'java', 'C++'], dtype=np.str)
print("Original Array:")
print(x)
capitalized_case = np.char.capitalize(x)
lowered_case = np.char.lower(x)
uppered_case = np.char.upper(x)
swapcased_case = np.char.swapcase(x)
titlecased_case = np.char.title(x)
print("\nCapitalized: ", capitalized_case)
print("Lowered: ", lowered_case)
print("Uppered: ", uppered_case)
print("Swapcased: ", swapcased_case)
print("Titlecased: ", titlecased_case)

Original Array:
['python' 'PHP' 'java' 'C++']

Capitalized:  ['Python' 'Php' 'Java' 'C++']
Lowered:  ['python' 'php' 'java' 'c++']
Uppered:  ['PYTHON' 'PHP' 'JAVA' 'C++']
Swapcased:  ['PYTHON' 'php' 'JAVA' 'c++']
Titlecased:  ['Python' 'Php' 'Java' 'C++']


90. Write a NumPy program to insert a space between characters of all the elements of a given array

In [192]:
x = np.array(['python exercises', 'PHP', 'java', 'C++'], dtype=np.str)
print("Original Array:")
print(x)
r = np.char.join(" ", x)
print(r)

Original Array:
['python exercises' 'PHP' 'java' 'C++']
['p y t h o n   e x e r c i s e s' 'P H P' 'j a v a' 'C + +']


91. Write a NumPy program to encode all the elements of a given array in cp500 and decode it again.

In [193]:
x = np.array(['python exercises', 'PHP', 'java', 'C++'], dtype=np.str)
print("Original Array:")
print(x)
encoded_char = np.char.encode(x, 'cp500')
decoded_char = np.char.decode(encoded_char,'cp500')
print("\nencoded =", encoded_char)
print("decoded =", decoded_char)

Original Array:
['python exercises' 'PHP' 'java' 'C++']

encoded = [b'\x97\xa8\xa3\x88\x96\x95@\x85\xa7\x85\x99\x83\x89\xa2\x85\xa2'
 b'\xd7\xc8\xd7' b'\x91\x81\xa5\x81' b'\xc3NN']
decoded = ['python exercises' 'PHP' 'java' 'C++']


92. Write a NumPy program to remove the leading whitespaces of all the elements of a given array.

In [194]:
x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'], dtype=np.str)
print("Original Array:")
print(x)
lstripped_char = np.char.lstrip(x)
print("\nRemove the leading whitespaces : ", lstripped_char)

Original Array:
[' python exercises ' ' PHP  ' ' java  ' '  C++']

Remove the leading whitespaces :  ['python exercises ' 'PHP  ' 'java  ' 'C++']


93. Write a NumPy program to split the element of a given array with spaces.

In [195]:
x = np.array(['Python PHP Java C++'], dtype=np.str)
print("Original Array:")
print(x)
r = np.char.split(x)
print("\nSplit the element of the said array with spaces: ")
print(r)

Original Array:
['Python PHP Java C++']

Split the element of the said array with spaces: 
[list(['Python', 'PHP', 'Java', 'C++'])]


94. Write a NumPy program to multiply a matrix by another matrix of complex numbers and create a new matrix of complex numbers.

In [196]:
x = np.array([1+2j,3+4j])
print("First array:")
print(x)
y = np.array([5+6j,7+8j])
print("Second array:")
print(y)
z = np.vdot(x, y)
print("Product of above two arrays:")
print(z)


First array:
[1.+2.j 3.+4.j]
Second array:
[5.+6.j 7.+8.j]
Product of above two arrays:
(70-8j)


95. Write a NumPy program to replace "PHP" with "Python" in the element of a given array.

In [197]:
x = np.array(['PHP Exercises, Practice, Solution'], dtype=np.str)
print("\nOriginal Array:")
print(x)
r = np.char.replace(x, "PHP", "Python")
print("\nNew array:")
print(r)


Original Array:
['PHP Exercises, Practice, Solution']

New array:
['Python Exercises, Practice, Solution']


96. Write a NumPy program to get the dates of yesterday, today and tomorrow

In [198]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-12-18
Today:  2020-12-19
Tomorrow:  2020-12-20


97. Write a NumPy program to count the number of days of specific month.

In [199]:
print("Number of days, February, 2016: ")
print(np.datetime64('2016-03-01') - np.datetime64('2016-02-01'))
print("Number of days, February, 2017: ")
print(np.datetime64('2017-03-01') - np.datetime64('2017-02-01'))
print("Number of days, February, 2018: ")
print(np.datetime64('2018-03-01') - np.datetime64('2018-02-01'))

Number of days, February, 2016: 
29 days
Number of days, February, 2017: 
28 days
Number of days, February, 2018: 
28 days


98. Write a NumPy program to find the first Monday in May 2020.

In [200]:
print("First Monday in May 2020:")
print(np.busday_offset('2020-05', 0, roll='forward', weekmask='Mon'))

First Monday in May 2020:
2020-05-04


99.  Write a NumPy program to find the number of weekdays in March 2020.

In [201]:
print("Number of weekdays in March 2020:")
print(np.busday_count('2020-03', '2020-04'))

Number of weekdays in March 2020:
22


100.  Write a NumPy program to convert numpy datetime64 to Timestamp.

In [202]:
from datetime import datetime
dt = datetime.utcnow()
print("Current date:")
print(dt)
dt64 = np.datetime64(dt)
ts = (dt64 - np.datetime64('1970-01-01T00:00:00Z')) / np.timedelta64(1, 's')
print("Timestamp:")
print(ts)
print("UTC from Timestamp:")
print(datetime.utcfromtimestamp(ts))

Current date:
2020-12-19 08:12:23.863872
Timestamp:
1608365543.863872
UTC from Timestamp:
2020-12-19 08:12:23.863872


<ipython-input-202-33e80203169d>:6: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts = (dt64 - np.datetime64('1970-01-01T00:00:00Z')) / np.timedelta64(1, 's')
